// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4z9Q-lasHcw_gbsYvNod5N8pGkqs3BfE',
    appId: '1:245218403052:web:30b6a6e919f731eeb03bc9',
    messagingSenderId: '245218403052',
    projectId: 'minvestforexapp-33dff',
    authDomain: 'minvestforexapp-33dff.firebaseapp.com',
    storageBucket: 'minvestforexapp-33dff.firebasestorage.app',
    measurementId: 'G-CRJG2SPE28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvzJ4crOk5FYhjHhkLCNX8gBtw5YC9qiU',
    appId: '1:245218403052:android:8da5ef21fd9e851bb03bc9',
    messagingSenderId: '245218403052',
    projectId: 'minvestforexapp-33dff',
    storageBucket: 'minvestforexapp-33dff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlMTFEpxSQPNMD_338j3oCnixX7otc_aU',
    appId: '1:245218403052:ios:c5d314db21e0ee24b03bc9',
    messagingSenderId: '245218403052',
    projectId: 'minvestforexapp-33dff',
    storageBucket: 'minvestforexapp-33dff.firebasestorage.app',
    iosClientId: '245218403052-2q6m9neo6l34jfnsferv5ui3h3r4fk68.apps.googleusercontent.com',
    iosBundleId: 'com.example.minvestForexApp',
  );
}
